[package]
name = "ddk-rs"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Andrew Walbran <qwandor@google.com>", "Anthony Stange <stange@google.com>"]
description = "Rust DDK for the Magenta kernel"
repository = "https://fuchsia.googlesource.com/ddk-rs/"

[dependencies]
ddk-sys = { path = "ddk-sys", version = "0.1.0" }
magenta = { path = "../magenta-rs", version = "0.2.0" }
