[package]
name = "mxruntime"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Raph Levien <raph@google.com>"]
description = "Rust bindings for Magenta runtime services"
repository = "https://fuchsia.googlesource.com/mxruntime/"
