[package]
name = "mxruntime"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Raph Levien <raph@google.com>"]
description = "Rust bindings for Zircon runtime services"
repository = "https://fuchsia.googlesource.com/mxruntime/"

[dependencies]
mxruntime-sys = { path = "mxruntime-sys", version = "0.1" }

fuchsia-zircon = { path = "../fuchsia-zircon", version = "0.3" }
fuchsia-zircon-sys = { path = "../fuchsia-zircon/fuchsia-zircon-sys", version = "0.3" }
